pipeline:
  # unit-tests:
  #   image: ruby:2.4.6-alpine
  #   commands:
  #     - apk add --no-cache --update postgresql-dev libxml2-dev libxslt-dev openssl libpq libffi-dev bash curl libstdc++ tzdata bash ca-certificates build-base ruby-dev libc-dev linux-headers postgresql-client postgresql git
  #     - cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
  #     - echo "America/Sao_Paulo" > /etc/timezone
  #     - export RAILS_ENV=test RACK_ENV=test DATABASE_URL=postgres://bonde@database/hub_api_test
  #     - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  #     - sleep 5;
  #     - psql -c "create database hub_api_test;" -hdatabase -U postgres -W postgres
  #     - psql -c "create role bonde SUPERUSER LOGIN;" -hdatabase -U postgres -W postgres
  #     - bundle install
  #     - rake db:migrate
  #     - bundle exec rspec spec
  #     - bundle exec rubocop app spec
  #   secrets: [ codacy_token, codeclimate_token, codecov_token ]
  #   when:
  #     event: [push, tag]

  # db-tests:
  #   image: nossas/docker-pgtap:develop
  #   commands:
  #     - /test.sh -h database -u bonde -w 3x4mpl3 -d hub_api_test -t './spec/**/**/*.sql'

  staging-publish:
    image: plugins/docker
    repo: nossas/bonde-server
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-api-rest:
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: webservers/api-rest
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    sidekick: migrations nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-mailchimp:
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: workers/mailchimp
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-mailers:
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: workers/mailers
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-donations:
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: cronjobs/donations
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-donations-recovery-from-metadata:
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: cronjobs/donations-recovery-from-metadata
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-donations-schedule-charges :
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: cronjobs/donations-schedule-charges
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]


  staging-deploy-donations-sync-balance-operations :
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: cronjobs/donations-sync-balance-operations
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]


  staging-deploy-donations-sync-gateway-transactions :
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: cronjobs/donations-sync-gateway-transactions
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  staging-deploy-templates-email:
    image: peloton/drone-rancher
    group: deploying
    url: http://cluster.bonde.org
    service: workers/templates-email
    docker_image: nossas/bonde-server:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  production-publish:
    image: plugins/docker
    repo: nossas/bonde-server
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  production-deploy-api-rest:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: webservers/api-rest
    sidekick: "migrations nossas/bonde-server:${DRONE_TAG##v}"
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  production-deploy-mailers:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: workers/mailers
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  production-deploy-mailchimp:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    group: deploying_prod
    service: workers/mailchimp
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  production-deploy-donations:
    image: peloton/drone-rancher
    group: deploying_prod
    url: http://cluster.bonde.org
    service: cronjobs/donations
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  production-deploy-donations-recovery-from-metadata:
    image: peloton/drone-rancher
    group: deploying_prod
    url: http://cluster.bonde.org
    service: cronjobs/donations-recovery-from-metadata
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  production-deploy-donations-schedule-charges :
    image: peloton/drone-rancher
    group: deploying_prod
    url: http://cluster.bonde.org
    service: cronjobs/donations-schedule-charges
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  production-deploy-donations-sync-gateway-transactions :
    image: peloton/drone-rancher
    group: deploying_prod
    url: http://cluster.bonde.org
    service: cronjobs/donations-sync-gateway-transactions
    docker_image: "nossas/bonde-server:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
    secrets: [ slack_webhook ]

services:
  database:
    image: postgres:9
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  queue:
    image: redis:3.2.4-alpine
